processbeat:
  period: 30s
  process:
    - kibana

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ES_HOST:elasticsearch:9200}'
  username: '${ES_USER:}'
  password: '${ES_PASS:}'
